Tela de listagem de trabalhadores
gamemGEAP/gamem-v2 pull request #17
Opened 2024-03-16 23:48 UTC by adautomoises

NECESSÁRIO USAR A [BRANCH NOVA](https://github.com/rafadot/GAMEM/pull/4) NO BACK-END COM A PAGINAÇÃO DOS TRABALHADORES.

2024-03-16 23:49 UTC, adautomoises commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tela de listagem de trabalhadores](https://trello.com/c/boa8jeIs/15-tela-de-listagem-de-trabalhadores)

2024-03-17 18:52 UTC, rafadot commented
Ao deletar um trabalhador não está atualizando a lista.

2024-03-17 19:44 UTC, rafadot commented on src/app/pages/gamem/trabalhadores/listar-trabalhadores/listar-trabalhadores.component.ts
> +  }
Analisar sugestão que eu mandei no DS

2024-03-17 19:44 UTC, rafadot commented on src/app/pages/gamem/trabalhadores/listar-trabalhadores/listar-trabalhadores.component.ts
> +  }
![image](https://github.com/gamemGEAP/gamem-v2/assets/116183725/14833c57-8e18-4d0b-b475-486e3e9ca459)

2024-03-17 19:44 UTC, rafadot commented on src/app/pages/gamem/trabalhadores/listar-trabalhadores/listar-trabalhadores.component.ts
> +  }
![image](https://github.com/gamemGEAP/gamem-v2/assets/116183725/d849d074-35f9-4681-a47b-86c49682f95a)

2024-03-17 19:45 UTC, rafadot requested changes
Precisando de correção

2024-03-17 22:55 UTC, rafadot approved these changes
ok

2024-03-17 22:56 UTC, merged